# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.qkuojlizvqbvsixiayyr
spring.datasource.password=Forzanapoli1926!

# Configurazione Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format_sql=true

server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.security.oauth2.client.registration.google.client-id=1081012580025-t7t200b30dps7hoe7av8u3m77ib4j9qp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile